name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: xainawan/api-gateway:latest

      - name: Build & Push Auth Service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          push: true
          tags: xainawan/auth-service:latest

      - name: Build & Push Doctor Service
        uses: docker/build-push-action@v5
        with:
          context: ./doctor-service
          push: true
          tags: xainawan/doctor-service:latest

      - name: Build & Push Patient Service
        uses: docker/build-push-action@v5
        with:
          context: ./patient-service
          push: true
          tags: xainawan/patient-service:latest

      - name: Build & Push Appointment Service
        uses: docker/build-push-action@v5
        with:
          context: ./appointment-service
          push: true
          tags: xainawan/appointment-service:latest

      - name: Build & Push Notification Service
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          push: true
          tags: xainawan/notification-service:latest
